services:
  - type: web
    name: trendhive
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: mainline.proxy.rlwy.net
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: bsMapmRGNiMXLsNGqQyxrlAmFSKPDIOl
      - key: DB_NAME
        value: railway
      - key: DB_PORT
        value: "41762"
